### ISSUE TITLE
无法在Vue2.x下引入

### ISSUE THREAD

**Issue by cccccpppppp** [wanglin2/markjs#15]
![image](https://user-images.githubusercontent.com/24277775/148345058-7859774b-0f31-4a0a-a1ef-57e00d5cf630.png)

**Comment by cccccpppppp** [comment]
已解决, 原因为该模块使用了[Public class fields](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes/Public_class_fields)语法, 而babel7默认不会处理node_modules导致webpack不识别这个语法.

**解决办法:**
**1. 在vue.config.js的transpileDependencies中加入该模块名**

 ```javascript
 transpileDependencies: [
  ...
  '@wanglin1994/markjs'
 ]
```
如果还是无效可能是`@vue/cli-plugin-babel`组件版本过低, 可升级该组件或者参考[这篇回答](https://stackoverflow.com/questions/59834578/vuejs-use-babel-plugin-proposal-class-properties)

**2. 将模块复制到src目录中引入** (应该需要较新版本的`@vue/cli-plugin-babel`)

**Comment by wanglin2** [comment]
是的，就是因为没有被babel编译，这种处理是可以的。
