### ISSUE TITLE
ShapePlugin激活后报错

### ISSUE THREAD

**Issue by mingfuyan** [wanglin2/markjs#18]
在shapePlugin激活后，`ShapePlugin`函数中
```js
else { // 超出数量限制 
            instance.observer.publish('COUNT-LIMIT', curEditingMarkItem)
            setIsCreateMarking(false)
        }
```
`curEditingMarkItem`报错，改成`instance.getState().curEditingMarkItem`后可正常运行。
本人新手，不知为何。

`nodejs 16.15`
脚手架 `create-react-app`

**Comment by wanglin2** [comment]
你好，确实是要添加的，这是bug，写漏了
