### ISSUE TITLE
如何通过输入坐标点的方式新增标注

### ISSUE THREAD

**Issue by mingfuyan** [wanglin2/markjs#19]
如何通过输入坐标点的方式新增标注？可以保证输入的坐标点是合法的。

**Comment by wanglin2** [comment]
修复了一下这个问题，可以这么创建
`mark0.createMarkItem({
        pointArr: [{"x":0.236875,"y":0.57890625},{"x":0.300625,"y":0.44265625},{"x":0.364375,"y":0.30640625},{"x":0.4625,"y":0.28640625},{"x":0.560625,"y":0.26640625},{"x":0.633125,"y":0.38390625},{"x":0.705625,"y":0.50140625},{"x":0.650625,"y":0.65515625},{"x":0.595625,"y":0.80890625},{"x":0.489375,"y":0.78515625},{"x":0.383125,"y":0.76140625},{"x":0.31,"y":0.67015625}]
      });`，具体可以参考推荐用法，npm版本上晚上回去更新~
